### ISSUE TITLE
my_followers_txt not working

### ISSUE THREAD

**Issue by DerLomo** [MaximPiessen/instagram_network_analysis#9]
After running the get_my_followers.py script, nothing appears to be writted on my_followers.txt
Does anyone have the same issue?

**Comment by rogerxaic** [comment]
Provided that you don't have any other error, in `bot.py`, line 80, replace `Following` with `Remove` and run again.

(FYI @MaximPiessen)

**Comment by shadow17t** [comment]
yes, i have the same issue

edit: line #77 of bot.py on 01 folder didn't work
following = self.driver.find_elements_by_xpath("//*[contains(text(), 'Following')]")

**Comment by rogerxaic** [comment]
Instagram have changed their UI, instead of showing you who you're following and letting you unfollow them, it now shows who you're not following and allowing you to follow them; which is the complete reverse logic – code needs to be adapted.

**Comment by MaximPiessen** [comment]
Thanks for the heads up. I'm not actively maintaining the code anymore. Feel free to contribute!

**Comment by navenduraisamy** [comment]
> Instagram have changed their UI, instead of showing you who you're following and letting you unfollow them, it now shows who you're not following and allowing you to follow them; which is the complete reverse logic – code needs to be adapted.

could you help me out.

**Comment by shadow17t** [comment]
> 
> 
> > Instagram have changed their UI, instead of showing you who you're following and letting you unfollow them, it now shows who you're not following and allowing you to follow them; which is the complete reverse logic – code needs to be adapted.
> 
> could you help me out.

change line #77 in bot.py into this:
following = self.driver.find_elements_by_xpath("//*[contains(@class, 'd7ByH')]")

at least this worked for me

**Comment by Martin-Hausleitner** [comment]
**Little Tutorial to get all you following**


1. [https://www.instagram.com/download/request/](https://www.instagram.com/download/request/) Choose JSON and Download
2. Open the Email Download the .zip (it takes a time to get the email)
3. Open the Folder followers_and_following
4. Upload the following.json to https://data.page/json/csv
5. Then only copy the line with the insta urls
(https://www.instagram.com/xxxxx
https://www.instagram.com/xxxx
https://www.instagram.com/xxx
https://www.instagram.com/xxxxxx)
into the my_followers.txt
6. Finished

**Comment by TylerTotally** [comment]
Great idea @Martin-Hausleitner 
I have my followers now recorded. Only issue is the program still doesnt know how to work with the new instagram UI, so when it searches for friends in common, it goes into an infinite loop. I also implemented the fix at line 77. Does anyone have a working fix in 2021?
Thanks guys!

**Comment by MaximPiessen** [comment]
Feel free to open a pull request if you have a working version!

**Comment by Martin-Hausleitner** [comment]
> Great idea @Martin-Hausleitner I have my followers now recorded. Only issue is the program still doesnt know how to work with the new instagram UI, so when it searches for friends in common, it goes into an infinite loop. I also implemented the fix at line 77. Does anyone have a working fix in 2021? Thanks guys!

if i have some time i will try
